server:
  port: 9000


spring:
  application:
    name: api-gateway # 应用名
  cloud:
    gateway:
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      routes:
        # id唯一标识，(可自定义)
        - id: PROVIDER-DEMO
          # 路由服务地址
          uri: lb://PROVIDER-DEMO
          # 路由拦截地址(断言)
          predicates:
            - Path=/PROVIDER-DEMO/**
eureka:
  client:
    service-url:
      # 注册Eureka Server集群
      defaultZone: http://127.0.0.1:8761/eureka

